### ISSUE TITLE
Add logout endpoint to api apps

### ISSUE THREAD

**Issue by stevenhorsman** [zowe/explorer-api-common#22]
*Engineering team info (eg https://github.com/zowe/explorer-jes/issues/4)*

**As a** zowe api user who has logged in,  
**I want** to be able to call an endpoint to log out 
**so that** can switch user credentials, or comply with security requirements.

*Details/notes*  
At the moment none of the zowe services are using the SSO facility, so the desktop logoff is not linked to the APIs
The SSO work should fix this in future, but that is currently blocked, so in the short term we should provide a temporary logoff endpoint to call on the rest api.

#### Acceptance Criteria

**Scenario 1:** Logout from datasets api
*Given* the datasets server api is running
*When* I do a GET request **with** account details 
*And* I do a GET request **without** providing account details 
*And* I do a POST request to logout the current user
*And* I do a GET request **without** providing account details 
*Then* I should get a 401 response status in only the final request.

**Scenario 2** Logout from jobs api
*Given* the jobs server api is running
*When* I do a GET request **with** account details 
*And* I do a GET request **without** providing account details 
*And* I do a POST request to logout the current user
*And* I do a GET request **without** providing account details 
*Then* I should get a 401 response status in only the final request.

**Comment by CForrest97** [comment]
Resolved in #25
